# Generated by Django 5.2.4 on 2025-08-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='https://res.cloudinary.com/dhjljccaa/image/upload/v1756458532/img_q2htj9.jpg', upload_to='profile_images'),
        ),
    ]
