# Generated by Django 5.2.5 on 2025-08-29 15:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dhjljccaa/image/upload/v1756458532/img_q2htj9.jpg', max_length=255, verbose_name='image'),
        ),
    ]
