# Generated by Django 5.2.5 on 2025-08-30 09:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_alter_post_image_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=cloudinary.models.CloudinaryField(default='img_q2htj9', max_length=255, verbose_name='image'),
        ),
    ]
